package com.marvis.mql.parser

enum class TokenType {
    // 数据引用
    OPEN, HIGH, LOW, CLOSE, VOL, OPI, AMOUNT,

    // 运算符
    PLUS, MINUS, MUL, DIV,
    GT, LT, GTE, LTE, EQ, NEQ,
    AND, OR, NOT,
    ASSIGN, COLON_ASSIGN,

    // 分隔符
    LPAREN, RPAREN, LBRACKET, RBRACKET,
    COMMA, SEMICOLON, COLON,

    // 关键字
    IF, THEN, ELSE, BEGIN, END,
    BUY, SELL, SHORT, COVER,
    BUYSHORT, SELLSHORT,
    CROSS, CROSS_UNDER,
    REF, HHV, LLV, HHVBARS, LLVBARS,
    BARSLAST, COUNT, SUM, EVERY,
    MA, EMA, SMA, DMA, WMA,
    MACD, MACDDIFF, MACDDEA,
    KDJ_K, KDJ_D, KDJ_J,
    RSI, BOLL_UPPER, BOLL_MID, BOLL_LOWER,
    SAR, ATR, DMI_PDI, DMI_MDI, DMI_ADX,
    STD, VAR, AVEDEV,
    ABS, MAX, MIN, MOD,
    IF_COND, VALUEWHEN, BACKSET,
    FILTER, DRAWLINE, DRAWICON, DRAWTEXT,
    STICKLINE, VERTLINE, PLAINTEXT,
    DRAWSL, DRAWNUMBER,
    ENTERLONG, EXITLONG, ENTERSHORT, EXITSHORT,
    BUYCOND, SELLCOND, SHORTCOND, COVERCOND,
    MARKETPOSITION, BKPRICE, SKPRICE, BKHIGH, SKLOW,
    AT, BARPOS, CURRENTTIME, CURRENTDATE,
    NUMTOSTR, STRFIND,
    IMPORT_PERIOD, IMPORT_DATA,
    PERIOD_MIN, PERIOD_HOUR, PERIOD_DAY, PERIOD_WEEK, PERIOD_MONTH,
    STICK, ALERT, PLAYSOUND,

    // 字面量
    NUMBER, STRING, IDENTIFIER,

    // 注释与空白
    LINE_COMMENT, BLOCK_COMMENT, WHITESPACE, NEWLINE,

    EOF
}

data class Token(
    val type: TokenType,
    val lexeme: String,
    val line: Int,
    val column: Int,
    val value: Any? = null
)
